version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345v
      - POSTGRES_USER=kuular
      - POSTGRES_DB=kuularbase
